# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()


  def login(self):
  	self.driver.find_element(By.ID, "login").send_keys("rizwanzafer2@gmail.com")
  	self.driver.find_element(By.ID, "password").send_keys("t5N$jL5cyNp3jQn")
  	self.driver.find_element(By.CSS_SELECTOR, "#wrapwrap > main > div > div > div > form > div.clearfix.oe_login_buttons.text-center.mb-1.pt-3 > button").click()
  	WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_app:nth-child(2) > .o_app_icon")))

  def test_createPOS(self):
    # Test name: Create POS
    # Step # | name | target | value | comment
    # 1 | open | /web |  | 
    self.driver.get("https://abcd17.odoo.com/web")
    # 2 | setWindowSize | 1366x728 |  | 
    self.driver.set_window_size(1366, 728)
    # 3 | click | css=.o_app:nth-child(2) > .o_app_icon |  | 
    self.login()
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > div.o_home_menu > div.o_home_menu_scrollable > div.o_apps > a:nth-child(2)")))
    self.driver.find_element(By.CSS_SELECTOR, "body > div.o_home_menu > div.o_home_menu_scrollable > div.o_apps > a:nth-child(2)").click()
    # 4 | click | linkText=Configuration |  |
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > header > nav > ul.o_menu_sections > li:nth-child(5) > a"))) 
    self.driver.find_element(By.LINK_TEXT, "Configuration").click()
    # 5 | click | css=.show > .dropdown-item:nth-child(2) > span |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(2) > span")))
    self.driver.find_element(By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(2) > span").click()
    # 6 | click | css=.o_list_button_add |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > div.o_action_manager > div > div.o_cp_controller > div > div:nth-child(2) > div.o_cp_left > div > div > button.btn.btn-primary.o_list_button_add")))
    self.driver.find_element(By.CSS_SELECTOR, "body > div.o_action_manager > div > div.o_cp_controller > div > div:nth-child(2) > div.o_cp_left > div > div > button.btn.btn-primary.o_list_button_add").click()
    # 7 | type | id=o_field_input_64 | New Shop | 
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "input.o_field_char.o_field_widget.o_input.o_required_modifier")))
    self.driver.find_element(By.CSS_SELECTOR, "input.o_field_char.o_field_widget.o_input.o_required_modifier").send_keys("New Shop")
    # 8 | click | css=.o_form_button_save |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_form_button_save")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_form_button_save").click()
  
  def test_createProduct(self):
    # Test name: Create Product
    # Step # | name | target | value | comment
    # 1 | open | /web |  | 
    self.driver.get("https://abcd17.odoo.com/web")
    # 2 | setWindowSize | 1366x728 |  | 
    self.driver.set_window_size(1366, 728)
    # 3 | click | css=.o_app:nth-child(2) > .o_app_icon |  | 
    self.login()
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_app:nth-child(2) > .o_app_icon")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_app:nth-child(2) > .o_app_icon").click()
    # 4 | click | linkText=Configuration |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > header > nav > ul.o_menu_sections > li:nth-child(5) > a")))
    self.driver.find_element(By.LINK_TEXT, "Configuration").click()
    # 5 | click | css=.o_menu_entry_lvl_3 > span |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_menu_entry_lvl_3 > span")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_menu_entry_lvl_3 > span").click()
    # 6 | click | css=.o_list_button_add |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_list_button_add")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_list_button_add").click()
    # 7 | type | id=o_field_input_34 | Coke | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "input.o_field_char.o_field_widget.o_input.o_field_translate.o_required_modifier")))
    self.driver.find_element(By.CSS_SELECTOR, "input.o_field_char.o_field_widget.o_input.o_field_translate.o_required_modifier").send_keys("Coke")
    # 8 | click | css=.o_form_button_save |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_form_button_save")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_form_button_save").click()

  def test_editPOS(self):
    # Test name: Edit POS
    # Step # | name | target | value | comment
    # 1 | open | /web |  | 
    self.driver.get("https://abcd17.odoo.com/web")
    # 2 | setWindowSize | 1366x728 |  | 
    self.driver.set_window_size(1366, 728)
    # 3 | click | css=.o_app:nth-child(2) > .o_app_icon |  | 
    self.login()
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_app:nth-child(2) > .o_app_icon")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_app:nth-child(2) > .o_app_icon").click()
    # 4 | click | linkText=Configuration |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > header > nav > ul.o_menu_sections > li:nth-child(5) > a")))
    self.driver.find_element(By.LINK_TEXT, "Configuration").click()
    # 5 | click | css=.show > .dropdown-item:nth-child(2) > span |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(2) > span")))
    self.driver.find_element(By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(2) > span").click()
    # 6 | click | css=.o_data_row:nth-child(2) > .o_list_char |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_data_row:nth-child(2) > .o_list_char")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_data_row:nth-child(2) > .o_list_char").click()
    # 7 | click | css=.o_form_sheet_bg |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_form_sheet_bg")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_form_sheet_bg").click()
    # 8 | click | css=.o_form_button_edit |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_form_button_edit")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_form_button_edit").click()
    # 9 | click | css=#other_devices > .o_setting_left_pane .custom-control-label |  | 
    # 10 | click | css=.o_form_button_save |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_form_button_save")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_form_button_save").click()
    # 11 | mouseDownAt | linkText=Reporting | 16.9375,7 | 

  def test_testcase2(self):
    # Test name: Testcase2
    # Step # | name | target | value | comment
    # 1 | open | /web |  | 
    self.driver.get("https://abcd17.odoo.com/web")
    # 2 | setWindowSize | 1366x728 |  | 
    self.driver.set_window_size(1366, 728)
    self.login()
    # 3 | click | css=.o_app:nth-chbody > div.o_home_menu > div.o_home_menu_scrollable > div.o_apps > a:nth-child(2)lf.login()
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > div.o_home_menu > div.o_home_menu_scrollable > div.o_apps > a:nth-child(2)")))
    self.driver.find_element(By.CSS_SELECTOR, "body > div.o_home_menu > div.o_home_menu_scrollable > div.o_apps > a:nth-child(2)").click()
    # 4 | click | css=.o_kanban_card_header |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_kanban_card_header")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_kanban_card_header").click()
    # 5 | click | linkText=Configuration |  |
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > header > nav > ul.o_menu_sections > li:nth-child(5) > a")))
    self.driver.find_element(By.LINK_TEXT, "Configuration").click()
    # 6 | click | css=.o_menu_entry_lvl_3 > span |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_menu_entry_lvl_3 > span")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_menu_entry_lvl_3 > span").click()
    # 7 | click | css=.o_data_row:nth-child(1) > .o_list_char |  | 

    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_data_row:nth-child(1) > .o_list_char")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_data_row:nth-child(1) > .o_list_char").click()
    # 8 | click | css=.o_form_button_edit |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_form_button_edit")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_form_button_edit").click()
    # 9 | click | id=o_field_input_43 |  |
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > div.o_action_manager > div > div.o_cp_controller > div > div:nth-child(2) > div.o_cp_left > div > div > div.o_form_buttons_edit > button.btn.btn-primary.o_form_button_save")))
    self.driver.find_element(By.CSS_SELECTOR, "body > div.o_action_manager > div > div.o_cp_controller > div > div:nth-child(2) > div.o_cp_left > div > div > div.o_form_buttons_edit > button.btn.btn-primary.o_form_button_save").click() 
  
  def test_delPOS(self):
    # Test name: Del POS
    # Step # | name | target | value | comment
    # 1 | open | /web |  | 
    self.driver.get("https://abcd17.odoo.com/web")
    # 2 | setWindowSize | 1363x728 |  | 
    self.driver.set_window_size(1363, 728)
    # 3 | click | css=.o_app:nth-child(2) > .o_app_icon |  | 
    self.login()
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > div.o_home_menu > div.o_home_menu_scrollable > div.o_apps > a:nth-child(2)")))
    self.driver.find_element(By.CSS_SELECTOR, "body > div.o_home_menu > div.o_home_menu_scrollable > div.o_apps > a:nth-child(2)").click()
    # 4 | click | linkText=Configuration |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > header > nav > ul.o_menu_sections > li:nth-child(5) > a")))
    self.driver.find_element(By.LINK_TEXT, "Configuration").click()
    # 5 | click | css=.show > .dropdown-item:nth-child(2) > span |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(2) > span")))
    self.driver.find_element(By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(2) > span").click()
    # 6 | click | css=.o_data_row:nth-child(2) .custom-control-label |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "body > div.o_action_manager > div > div.o_content > div > div > table > tbody > tr:nth-child(2) > td.o_list_record_selector > div")))
    self.driver.find_element(By.CSS_SELECTOR, "body > div.o_action_manager > div > div.o_content > div > div > table > tbody > tr:nth-child(2) > td.o_list_record_selector > div").click()
    # 7 | click | css=.btn-group > .btn-group:nth-child(2) > .o_dropdown_toggler_btn |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".btn-group > .btn-group:nth-child(2) > .o_dropdown_toggler_btn")))
    self.driver.find_element(By.CSS_SELECTOR, ".btn-group > .btn-group:nth-child(2) > .o_dropdown_toggler_btn").click()
    # 8 | click | linkText=Delete |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Delete")))
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    # 9 | click | css=.btn-primary > span |  | 
    WebDriverWait(self.driver, 20).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".btn-primary > span")))
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary > span").click()
  
